name: spot
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  stylish_bottom_bar: ^1.1.0
  http: ^0.13.3
  image_picker: ^0.8.4+4
  image: ^4.0.15

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

# 앱 아이콘
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"


  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/images/O!.png
    - assets/images/logo.png
    - assets/images/top.png
    - assets/images/bottom.png
    - assets/images/logo_app.png
    - assets/images/dot.png
    - assets/images/new.png
    - assets/images/refr.png
    - assets/images/zero.png
    - assets/images/existing.png
    - assets/images/wash.png
    - assets/images/ex3.png
    - assets/images/ex4.png
    - assets/images/finding.png
    - assets/images/result/STAR.png
    - assets/images/result/BELL.png
    - assets/images/result/sttar.png
    - assets/images/appliance/example.png
#   온보딩 닷
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
#   아이폰
    - assets/images/phone1.png
    - assets/images/phone2.png
    - assets/images/phone3.png
    - assets/images/phone4.png
#   유저
    - assets/images/user/3DOT.png
    - assets/images/user/hand.png
    - assets/images/user/camera.png
    - assets/images/user/newpage.png
    - assets/images/copy.png
#   가전 상세 페이지
    - assets/images/re/detail.png
    - assets/images/re/Q1.png
    - assets/images/re/Q2.png
    - assets/images/re/Q3.png
    - assets/images/re/Q4.png
    - assets/images/re/mic.png
    - assets/images/re/fix.png
    - assets/images/re/re-detail.png
    - assets/images/re/text.png
    - assets/images/re/dots.png
    - assets/images/refr.png
    - assets/images/re/redetail.png
    - assets/images/wash/washdetail.png
    - assets/images/wash/wwash.png
    - assets/images/wash/wwwash.png
    - assets/images/codedetail.png
    - assets/images/
#   카메라
    - assets/images/camera/frame.png
#   인식 완료
    - assets/images/finished/star.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900


  uses-material-design: true


